// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"echochat/models"
	"fmt"
)

func getMethod(provider models.ProviderModel) string {
	if provider.Method == "" {
		return "'telegram'"
	}

	return fmt.Sprintf("'%v'", provider.Method)
}

func getFormBodyID(provider models.ProviderModel) string {
	if provider.ID == "" {
		return "providerAddForm"
	}

	return "providerEditForm"
}

func getServicesID(provider models.ProviderModel) string {
	if provider.ID == "" {
		return "addServiceFromProviderForm"
	}

	return "editServiceFromProviderForm"
}

func getServiceFormID(provider models.ProviderModel) string {
	if provider.ID == "" {
		return "addServiceFromNewlyAddedProviderForm"
	}

	return "addServiceFromExistingAddedProviderForm"
}

func ProviderFormBody(provider models.ProviderModel, formID string, services []models.ServiceModel) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(formID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 41, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"flex flex-col self-stretch flex-1 min-h-0\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`{ method: ` + getMethod(provider) + ` }`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 41, Col: 120}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><label for=\"inpUrl\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">URL (*)</label> <input autocomplete=\"off\" id=\"inpUrl\" name=\"url\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(provider.URL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 43, Col: 76}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"https://provider.com\" required> <label for=\"method\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Method (*)</label> <select x-model=\"method\" id=\"method\" name=\"method\" class=\"transition-colors block px-2 py-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\"><option value=\"telegram\">Telegram</option> <option value=\"web\">Web</option> <option value=\"whatsapp\">WhatsApp</option> <option value=\"manual\">Manual</option></select><div class=\"flex flex-col mt-2 method\" x-show=\"method === &#39;web&#39;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if provider.Method == "web" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label for=\"supportUsername\" class=\"font-semibold px-3 py-1 text-sm\">Support Username (*)</label> <input value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(provider.MethodData["support_username"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 54, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" :required=\"method === &#39;web&#39;\" autocomplete=\"off\" id=\"supportUsername\" name=\"supportUsername\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"Username\"> <label for=\"supportPassword\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Support Password (*)</label> <input value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(provider.MethodData["support_password"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 56, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" :required=\"method === &#39;web&#39;\" autocomplete=\"off\" id=\"supportPassword\" name=\"supportPassword\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"********\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label for=\"supportUsername\" class=\"font-semibold px-3 py-1 text-sm\">Support Username (*)</label> <input :required=\"method === &#39;web&#39;\" autocomplete=\"off\" id=\"supportUsername\" name=\"supportUsername\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"Username\"> <label for=\"supportPassword\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Support Password (*)</label> <input :required=\"method === &#39;web&#39;\" autocomplete=\"off\" id=\"supportPassword\" name=\"supportPassword\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"********\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"flex flex-col mt-2 method\" x-show=\"method === &#39;telegram&#39;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if provider.Method == "telegram" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label for=\"telegramChatId\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Telegram Chat ID (*)</label> <input value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(provider.MethodData["telegram_chat_id"])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 67, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" :required=\"method === &#39;telegram&#39;\" autocomplete=\"off\" id=\"telegramChatId\" name=\"telegramChatId\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"-104xxxx\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label for=\"telegramChatId\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Telegram Chat ID (*)</label> <input :required=\"method === &#39;telegram&#39;\" autocomplete=\"off\" id=\"telegramChatId\" name=\"telegramChatId\" class=\"webInp transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"-104xxxx\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><label for=\"alias\" class=\"mt-2 font-semibold px-3 py-1 text-sm\">Alias</label> <input autocomplete=\"off\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(provider.Alias)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 74, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" id=\"alias\" name=\"alias\" class=\"transition-colors block p-2 ps-3 text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:bg-white text-sm focus:border-gray-500 outline-none\" type=\"text\" placeholder=\"Provider Name\"><div id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(getServicesID(provider))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components\provider_form_body.templ`, Line: 75, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"flex flex-col flex-1 py-2 px-3 mt-2 mb-2 min-h-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if provider.ID != "" {
			templ_7745c5c3_Err = AddServiceFromProviderForm(provider, getServiceFormID(provider), services).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><hr class=\"py-2\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
